packages:
  - "packages/linea-state-verifier"
  - "packages/linea-ccip-gateway"
  - "packages/linea-ens-resolver"
  - "packages/linea-ens-app"
  - "packages/linea-ens-subgraph"
  - "packages/poh-signer-api"
