services:
  ens-web3signer:
    container_name: ens-web3signer
    image: consensys/web3signer:latest
    profiles: ["l2", "debug"]
    ports:
      - "9000:9000"
    command:
      # - --key-store-path=/keyFiles/
      # - --http-host-allowlist=*
      - --config-file=/config/web3signer-config.yaml

      - eth1
    volumes:
      - ./keyFiles/:/keyFiles/
      - ./config/config.yaml:/config/web3signer-config.yaml
    networks:
      - ens-network

networks:
  ens-network:
    external: true
