name: Build and Publish Gateway
on:
  push:
    branches:
      - main
    paths:
      - "packages/gateway/**"
  pull_request:
    branches:
      - main
    paths:
      - "packages/gateway/**"
  release:
    types:
      - released

jobs:
  gateway-build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            packages/gateway
            packages/linea-verifier
            pnpm-workspace.yaml
            pnpm-lock.yaml
          sparse-checkout-cone-mode: false

      - name: Set Docker Tag
        id: docker-tag
        if: ${{ github.event_name != 'release' }}
        run: echo "DOCKER_TAG=${GITHUB_SHA:0:7}-$(date +%s)-gateway" | tee $GITHUB_ENV

      - name: Set Docker Tag - Release
        id: docker-tag-release
        if: ${{ github.event_name == 'release' }}
        run: echo "DOCKER_TAG=${GITHUB_SHA:0:7}-$(date +%s)-gateway-${GITHUB_REF#refs/tags/}" | tee $GITHUB_ENV

      - name: Login to Docker Repository
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REPO_USER }}
          password: ${{ secrets.DOCKER_REPO_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Image Build and Publish
        uses: docker/build-push-action@v4
        with:
          build-args: |
            ENV_FILE=.env.production
          file: ./packages/gateway/Dockerfile
          context: ./
          push: true
          tags: consensys/linea-resolver:${{ env.DOCKER_TAG }}
