name: Run l2-contracts unit tests

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/l2-contracts/**"

jobs:
  l2-contracts-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./packages/l2-contracts

    steps:
      - uses: actions/checkout@v4

      - name: For act to work (local testing)
        run: npm -g install yarn

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: yarn install --immutable --immutable-cache --check-cache

      - name: Run test
        run: yarn test
